[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Ross Hill <ross@rosshill.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.4.1"
num = "0.3.1"
image = "0.23.12"
itertools-num = "0.1.3"
actix-http = "2.2.0"
colorous = "1.0.3"